module.exports =[
    {title: "The Best Super Foods for a Super You", pic: "http://localhost:8080/img/superfood.a966ecae.jpg",
    description: "A quick guide to understanding super foods and how they can help in your life.",
    author: "Michelle Salazar", story: ["What is a superfood? You probably heard that term before, but might not know what it means. Basically, it is a nutrient rich food with health benefits. So now that you know what a super food is, which ones are the best and why?",
    "Kale is a highly popular super food, which is high in vitamin A, C, and K. It also tastes great in smoothies, and can be cooked in a variety of ways! Other leafy greens like spinach and swiss chard also offer similar health benefits.",
    "Berries are also a great superfood! They're filled with nutrients and are delicious. They're a great treat if you're craving something sweet, or if you're trying to get your youngsters to eat healthy.",
    "Nuts and seeds are fiber filled and should also be included in this list, especially because of the varieties they come in. With such a variety, there is a high chance you will find a food in this category you love. Additionally, nuts and seeds tend to be high in protein which makes them good superfood staples. Nuts and seeds are also vegan and vegetarian friendly, which gives them even more points in their favor.",
    "These food items were just the tip of the iceberg when it comes to superfood, but hopefully you now have more of an idea of what a superfood is. There is no universal technical definition though, so be wary when you hear advertisers claim their food as a superfood, and always actually look at the nutrition information on your food and compare it to other foods."
    ]},
   
    {title: "Tips for an Awesome Gym Workout", pic: "http://localhost:8080/img/abWorkout.e7efe3f2.jpeg", 
    description: "Beginner advice on how to get the most out of your gym workout.",
    author: "Maggie Smith", story: [
    "Everyone has different experiences with gyms. Every person and every gym are different, so there aren't any magical tips for a great visit, but here are my suggestions for the best gym experiences.",
    "Come prepared. Make sure to have the essentials with you: a water bottle, sneakers, a change of clothes, a hair tie if you need it. I suggest keeping a backup bag in your car with those gym essentials for the days where you forget something, or make an unscheduled visit to your gym. I also suggest adding headphones to that backup bag, and creating a playlist beforehand to listen to while you workout. The most helpful thing that gets me through a workout is probably having the right music.",
    "Step outside of your comfort zone! Don't be afraid to try a new machine or exercise. Everyone was new to working out at some point, and trying something new is the best way to find out which workouts you love and to keep challenging your body. To avoid getting bored of your workout routine, I suggest trying something new at least every month, if not much more often.",
    "Remember to have fun. You're more inclined to work out more often if you actually enjoy it. So take time to find the gym and workouts that work best for you."
    ]},

    {title: "Why Workout?", pic: "http://localhost:8080/img/motivation.b33b599b.jpeg", 
    description: "Every now and then, we all need motivation to remind us why we work out in the first place.",
    author: "Michelle Salazar", story: [
    "Oh no! You discovered staying healthy is not always super fun, and part of you wants to go back to binging Netflix and cheese fries all day long while you just lie on our couch and never workout again. Okay, maybe it's not that extreme. Either way, we all have days where we want to stray from our goals and skip out on what we said we were going to do. While taking a break every now and then is completely normal, here are some things to think about when you want to give up all together.",
    "Do you remember how accomplished you felt when you met your first goal? You set your goals in order to be the best version of yourself, and following through on as many of those goals as you can will lead to awesome feelings of self accomplishment. If your goals seem too unattainable, break them down into steps. Even if your not where you want to be yet, you should feel proud of how far you have come, and with each step towards the you that you want to be, you should feel even prouder. There will always be room for self improvement, so celebrate the little steps and work hard to meet your next goal.",
    "Focusing on your health can lead to a longer and happier life. Being humans, we depend on our bodies a lot. It only makes sense to treat them the best we can. Regularly working out and eating healthy helps give you the strongest, most functional body. Plus working out has even been known to produce  endorphins, which are related to the feeling of pleasure. So even though workouts may not always feel fun, overall they have the potential to add to your enjoyment of life.",
    "I know a lot of the times when I give up on my goals it has to do with me feeling defeated and incapable of accomplishing them. Hopefully, that is not your current scenario, but if it is, let me be the first to tell you that you are being ridiculous. You are more capable than you think you are. Push a deadline back if you have to, have patience, and just keep trying. Even if your goal stays out of reach, you will feel better knowing you tried your best then just giving up. And chance are, you will reach your goals. You can do it!"
    ]},
];