module.exports =[
    {title: "The Best Super Foods for a Super You", pic: "../../superfood.jpg",
    description: "A quick guide to understanding super foods and how they can help in your life",
    author: "Michelle Salazar", story: ["What is a superfood? You probably heard that term before, but might not know what it means. Basically, it is a nutrient rich food with health benefits. So now that you know what a super food is, which ones are the best and why?",
    "Kale is a highly popular super food, which is high in vitamin A, C, and K. It also tastes great in smoothies, and can be cooked in a variety of ways! Other leafy greens like spinach and swiss chard also offer similar health benefits.",
    "Berries are also a great superfood! They're filled with nutrients and are delicious. They're a great treat if you're craving something sweet, or if you're trying to get your youngsters to eat healthy.",
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec sagittis augue. Mauris vel eros lacinia, molestie sapien ornare, viverra turpis. Etiam facilisis nisl tortor, quis mollis erat convallis et. Donec vel venenatis augue, id maximus augue. Quisque aliquam vehicula arcu vitae aliquam. Integer imperdiet bibendum quam, id dignissim tellus vulputate nec. Aenean placerat malesuada mauris a porttitor. Maecenas vel ex nisl. Nunc et placerat elit. Donec aliquam lectus in elit egestas, quis egestas leo dignissim. Nulla vel rhoncus urna. Donec ac lacus est. Aliquam et interdum urna, ut pharetra eros. Praesent interdum nec dui a lobortis.",
    "Suspendisse vulputate leo condimentum ex mollis lobortis. Proin mollis ultrices augue in ultrices. Nunc tristique finibus urna, ut ultricies enim ultricies ac. Nam nec rhoncus enim, semper consequat risus. Quisque blandit vitae ante a tincidunt. In hac habitasse platea dictumst. Mauris molestie lectus eget tempor lacinia."
    ]},
   
    {title: "Five Quick Core Workouts", pic: "../../abWorkout.jpeg", 
    description: "Life gets busy. When there's no time to go to the gym, you can still be healthy and do these quick workouts",
    author: "Maggie Smith", story: [
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec sagittis augue. Mauris vel eros lacinia, molestie sapien ornare, viverra turpis. Etiam facilisis nisl tortor, quis mollis erat convallis et. Donec vel venenatis augue, id maximus augue. Quisque aliquam vehicula arcu vitae aliquam. Integer imperdiet bibendum quam, id dignissim tellus vulputate nec. Aenean placerat malesuada mauris a porttitor. Maecenas vel ex nisl. Nunc et placerat elit. Donec aliquam lectus in elit egestas, quis egestas leo dignissim. Nulla vel rhoncus urna. Donec ac lacus est. Aliquam et interdum urna, ut pharetra eros. Praesent interdum nec dui a lobortis.",
    "Suspendisse vulputate leo condimentum ex mollis lobortis. Proin mollis ultrices augue in ultrices. Nunc tristique finibus urna, ut ultricies enim ultricies ac. Nam nec rhoncus enim, semper consequat risus. Quisque blandit vitae ante a tincidunt. In hac habitasse platea dictumst. Mauris molestie lectus eget tempor lacinia.",
    "Nullam vitae tincidunt eros. Duis convallis, nisl at consectetur lobortis, magna est laoreet ligula, non vehicula lectus urna at leo. Suspendisse sit amet ipsum ligula. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris vel mauris non est finibus sodales. Morbi congue magna justo, nec eleifend nulla commodo quis. Fusce a diam pulvinar, maximus est at, sollicitudin augue. Interdum et malesuada fames ac ante ipsum primis in faucibus. Integer sit amet ante vel nunc pellentesque interdum at eu tortor. Aenean id congue dolor. Cras vulputate sollicitudin diam, sed interdum sem venenatis et.",
    "Curabitur tincidunt faucibus auctor. Maecenas sit amet sapien lorem. Sed interdum purus faucibus fermentum lobortis. Nulla facilisi. Nullam faucibus, libero vitae porttitor consequat, neque est hendrerit nulla, ut eleifend est felis sed ligula. Curabitur semper faucibus nulla sed rhoncus. Nulla quam velit, pharetra vitae lacinia ut, commodo nec ipsum. Aenean eu facilisis erat. Donec sagittis nulla dui, aliquam fringilla velit porttitor at. Ut mattis dui ornare erat congue, nec molestie turpis fermentum. Mauris magna sapien, venenatis a condimentum id, convallis non felis. Donec id turpis ac velit tincidunt congue. Phasellus malesuada sed est at elementum."
    ]},

    {title: "Why Workout?", pic: "../../motivation.jpeg", 
    description: "Every now and then, we all need motivation to remind us why we work out in the first place",
    author: "Michelle Salazar", story: [
    "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec sagittis augue. Mauris vel eros lacinia, molestie sapien ornare, viverra turpis. Etiam facilisis nisl tortor, quis mollis erat convallis et. Donec vel venenatis augue, id maximus augue. Quisque aliquam vehicula arcu vitae aliquam. Integer imperdiet bibendum quam, id dignissim tellus vulputate nec. Aenean placerat malesuada mauris a porttitor. Maecenas vel ex nisl. Nunc et placerat elit. Donec aliquam lectus in elit egestas, quis egestas leo dignissim. Nulla vel rhoncus urna. Donec ac lacus est. Aliquam et interdum urna, ut pharetra eros. Praesent interdum nec dui a lobortis.",
    "Suspendisse vulputate leo condimentum ex mollis lobortis. Proin mollis ultrices augue in ultrices. Nunc tristique finibus urna, ut ultricies enim ultricies ac. Nam nec rhoncus enim, semper consequat risus. Quisque blandit vitae ante a tincidunt. In hac habitasse platea dictumst. Mauris molestie lectus eget tempor lacinia.",
    "Nullam vitae tincidunt eros. Duis convallis, nisl at consectetur lobortis, magna est laoreet ligula, non vehicula lectus urna at leo. Suspendisse sit amet ipsum ligula. Interdum et malesuada fames ac ante ipsum primis in faucibus. Mauris vel mauris non est finibus sodales. Morbi congue magna justo, nec eleifend nulla commodo quis. Fusce a diam pulvinar, maximus est at, sollicitudin augue. Interdum et malesuada fames ac ante ipsum primis in faucibus. Integer sit amet ante vel nunc pellentesque interdum at eu tortor. Aenean id congue dolor. Cras vulputate sollicitudin diam, sed interdum sem venenatis et."
    ]},
];